name: fritzing
version: 1
summary: Fritzing is an open source PCB design tool
description: Easy-to-use, electronic design software.  Fritzing is an open source project designed to help one transition from a prototype to a finished project.  Aimed at users who want to produce or document circuits and experiments, one starts by building a physical prototype, then recreating it with Fritzing’s graphical editor.  From there one can generate a schematic, PCB artwork, and PCB production files.


apps:
    fritzing:
        command: fritzlaunch
        plugs: [x11, unity7, home, opengl, network]

parts:
    launcher:
        plugin: copy
        files:
            fritzlaunch: bin/fritzlaunch
        
    libgit2:
        plugin: cmake
        source: https://github.com/libgit2/libgit2.git
        source-branch: maint/v0.23
        source-type: git
        build-packages:
            -   libssl-dev
    fritzing:
        after: [libgit2]
        plugin: qmake
        source: ./fritzing-src/
        #source-type: git
        project-file: fritzing-snapcraft.pro
        build-packages:
            -   cmake
            -   libssl-dev
            -   libboost-dev
            -   libboost1.58-dev
            -   libgl1-mesa-dev
            -   libgles2-mesa
            -   libgles2-mesa-dev
            -   libglu1-mesa-dev
            -   libqt5concurrent5
            -   libqt5serialport5
            -   libqt5serialport5-dev
            -   libqt5svg5-dev
            -   mesa-common-dev
            -   qt5-qmake
            -   qtbase5-dev
            -   qtbase5-dev-tools
            -   sqlite3
        stage-packages:
            -   libgles2-mesa
            -   libqt5concurrent5
            -   libqt5serialport5
            -   qt5-qmake
            -   qtbase5-dev-tools
            -   sqlite3

